### ISSUE TITLE
add 'no anti-aliasing mode'

### ISSUE THREAD

**Issue by Kyogre** [sblask/webextension-enhanced-image-viewer#2]
1. it misses the most important scaling mode - "no anti-aliasing mode" (many people would like original crispy pixelated images), that can be toggled via CSS code:
html > body > img:only-child {
image-rendering: -moz-crisp-edges;
}
2. it will be perfect if this extension could toggle "no anti-aliasing mode" only when image scaled is bigger than 100% - that way when images zoomed-out (or have resolution less than your display) will be anti-aliased, and zoomed-in images (or those have resolution better than display resolution) will be displayed in original non-smoothed view. If you don't understand that I mean you can check any Faststone viewer software and look for scaling options.

**Comment by sblask** [comment]
I am not really interested in implementing and maintaining an edge case that I won't use and only works on browsers that I don't use. This has been around in Firefox for ages and apparently didn't gain any traction.

**Comment by Kyogre** [comment]
what do you mean by "only works on browsers that I don't use"? I am using Firefox 55.0.3 and that CSS code works fine and that feature will be very useful for cases when you need to see original image or when you need to compare images.

**Comment by sblask** [comment]
And I don't use Firefox anymore.

You'll have to find another solution for your use case.
