### ISSUE TITLE
Feature request add custom CSS styling for #info (AKA popup)

### ISSUE THREAD

**Issue by Acid-Crash** [sblask/webextension-enhanced-image-viewer#3]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
I would be nice to add functionality of basic CSS styling for the #info section. 
For example Font-family/style/width/size/color and border/shadows size and style.

With this, a style can be matched with the one from the browser.

**Comment by sblask** [comment]
Not interested in doing this, but if anybody wants to give it a go, they can give it a go.
