### ISSUE TITLE
The ability to restrict the rotating to current tab only

### ISSUE THREAD

**Issue by artquest** [sblask/webextension-enhanced-image-viewer#7]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Is it possible to restrict the rotating to current tab only? If I have other images opened in other tabs they are rotated also.
And I agree with DimkaDim, it would be nice to have an option to disable the info popup.

**Comment by sblask** [comment]
No time to implement this. If someone wants to send a PR for it, please reopen.
